server:
  port: 6001

spring:
  application:
    name: micsroservice-zuul

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
#      defaultZone: http://localhost:7001/eureka # 单机的使用的
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/,http://www.eureka7003.com:7003/eureka/
       
  instance:
    instance-id: microservice-zuul-6001
    prefer-ip-address: true

zuul:
  prefix: /etcp # 添加公共的前缀
  ignored-services: microservice-provider # 忽略单个服务ID
#  ignored-services: "*" # 忽略多个服务ID，使用*号，注意需要添加双引号哟，否则是char类型的，会报错，当然还可以以集合的形式进行忽略指定的多个服务ID
  routes:
    microservice.serviceId: microservice-provider
    microservice.path: /java98k/**

info:
  app.name: learning-microservice-springcloud
  company.name: huazai-studio
  build.artifactId: $project.artifactId$
  build.version: $project.version$